image: qlik/gradle
 
pipelines:
  default:
    - step:
        script:
          - gradle build
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build/libs/mvnrepo-backend_old.jar"